

sap.ui.jsview("ui5applicationiii3.Start", {

createContent: function (oController) {
    
    return new sap.m.Page( {
            title: "Start",
            content: [
                new sap.m.Label({
                text: ""
            }),
            new sap.ui.core.HTML({
              content :   '  <div class="inner">'
              +'  <header style="display: table-cell;">'
              +'<h1>AkuaJs for SAP UI5</h1>'
              +' <h3>The AkuaJs Analytical Engine for SAP UI5</h3>'
              +' </header>'
              +'<div style="display: table-cell;">'
              +' <img src="images/tesseract.png" style="height:100px;vertical-align:botton;margin-left:100px;padding-top:20px" />'
              +'</div>'
              +''
              +''
              +'<section id="downloads" class="clearfix">'
              +' <a href="https://rawgit.com/Qrist0ph/AkuaJs/latest/bin/AkuaJUi5.zip" id="download-zip" class="button"><span>Download .zip</span></a>'
              +'<a href="https://github.com/Qrist0ph/AkuaJs-UI5" id="view-on-github" class="button"><span>View on GitHub</span></a>'
              +'</section>'
              +''  
              +'<div id="wrapper"> <h3>Why use AkuaJs</h3>'
              +'<ul>'
              +'<li>Create awesome Visualizations based on one unified Data Model</li>'
              +'<li>Choose from a variety of different charts</li>'
              +'<li>Build interactive maps to display sales or financial information </li>'
              +'<li>Ready for mobile app development</li>'
              +'<li>Easily extend it to incorporate your favorite charting engine</li>'
              +' <li>Free for non commercial usage and during development</li>'
              +''
              +'</ul>'
              +'</div>'
              +''
              +''
              +'<h3>Using AkuaJs</h3>'
              +'Add dependencies to the head section of your main html:'
              +'<pre><code>' 
              + '&lt;script src=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/libs/D3/d3.min.js&quot;&gt;&lt;/script&gt;    <br/>'
              +'&lt;script data-main=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/main.js&quot; src=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/libs/require.js&quot;&gt;&lt;/script&gt;<br/>'
              +'&lt;link rel=&quot;stylesheet&quot; href=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/libs/nvd3'
              + '</code></pre>'
              +''
              +''
              +''
              +'Use it like that: '              
               +'<pre><code>' 
            +'&lt;!DOCTYPE html&gt;<br/>'
+'&lt;html&gt;<br/>'
+'&lt;head&gt;<br/>'
+'&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;<br/>'
+'&lt;meta http-equiv=&#39;Content-Type&#39; content=&#39;text/html;charset=UTF-8&#39; /&gt;<br/>'
+'    <br/>'
+'&lt;script src=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/libs/D3/d3.min.js&quot;&gt;&lt;/script&gt;    <br/>'
+'&lt;script data-main=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/main.js&quot; src=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/libs/require.js&quot;&gt;&lt;/script&gt;<br/>'
+'&lt;link rel=&quot;stylesheet&quot; href=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/libs/nvd3/nv.d3.min.css&quot; type=&quot;text/css&quot; /&gt;    <br/>'
+'    <br/>'
+'&lt;script src=&quot;https://openui5.hana.ondemand.com/resources/sap-ui-core.js&quot;<br/>'
+'        id=&quot;sap-ui-bootstrap&quot;<br/>'
+'        data-sap-ui-libs=&quot;sap.m&quot;<br/>'
+'        data-sap-ui-theme=&quot;sap_bluecrystal&quot;&gt;<br/>'
+'&lt;/script&gt;<br/>'
+'   <br/>'
+'&lt;script&gt;<br/>'
+'jQuery.sap.registerModulePath(&#39;AkuaJs&#39;, &#39;https://rawgit.com/Qrist0ph/AkuaJs-UI5/latest/build/AkuaJs&#39;);<br/>'
+'jQuery.sap.require(&quot;AkuaJs.PieChart&quot;);<br/>'
+'<br/>'
+' require([&quot;core/CoreBundle&quot;], function() { <br/>'
+'    eJune = E(D(&quot;Month&quot;), &quot;June&quot;);<br/>'
+'    eAugust = E(D(&quot;Month&quot;), &quot;August&quot;);<br/>'
+'    ePoland = E(D(&quot;Country&quot;), &quot;Poland&quot;);        <br/>'
+'    eCar = E(D(&quot;Product&quot;), &quot;Car&quot;);<br/>'
+'    eBike = E(D(&quot;Product&quot;), &quot;Bike&quot;);<br/>'
+'    eBoat = E(D(&quot;Product&quot;), &quot;Boat&quot;);<br/>'
+'    eCost = E(D(&quot;Measure&quot;), &quot;Costs&quot;);<br/>'
+'    eRevenue = E(D(&quot;Measure&quot;), &quot;Revenue&quot;);   <br/>'
+'                <br/>'
+'    new AkuaJs.PieChart({<br/>'
+'             axis0: A({<br/>'
+'             crosslists:<br/>'
+'                [ TCL([<br/>'
+'                     T([eCar]), T([eBike]), T([eBoat])<br/>'
+'                    ])]<br/>'
+'                    }),<br/>'
+'             slicer: T([eCost]),<br/>'
+'<br/>'
+'			 connection : LocalCubeConnection(HyperCube(SDTL([ <br/>'
+'					T([eAugust, eCar, eCost],440)<br/>'
+'					,T([eAugust, eBike, eCost],77)    <br/>'
+'					,T([eAugust, eBoat, eCost],120)]))),<br/>'
+'             colors:[&quot;#FFD700&quot;, &quot;#F4A460&quot;,&quot;#990000&quot;],<br/>'
+'             numberFormat:&#39;,.2&#39;<br/>'
+'<br/>'
+'}).placeAt(&#39;content&#39;)<br/>'
+' });<br/>'
+'<br/>'
+'&lt;/script&gt;<br/>'
+'&lt;/head&gt;<br/>'
+'&lt;body class=&quot;sapUiBody&quot; role=&quot;application&quot;&gt;<br/>'
+'    &lt;div id=&quot;content&quot;&gt;&lt;/div&gt;<br/>'
+'&lt;/body&gt;<br/>'
+'<br/>'
+'&lt;/html&gt;<br/>'
+'<br/>'
              + '</code></pre>'
              +'<hr/>'
            
              +''
              +'Copyright © 2015  <a href="https://github.com/Qrist0ph">Christoph Au&szlig;em</a> <br/> <a href="https://de.linkedin.com/pub/christoph-au%C3%9Fem/21/8b4/27">'
              +'<img src="https://static.licdn.com/scds/common/u/img/webpromo/btn_liprofile_blue_80x15_de_DE.png?locale=" width="80" height="15" border="0" alt="Profil von Christoph Außem auf LinkedIn anzeigen">'
             
              +'<br/>'
              +'<a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/3.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/">Creative Commons Attribution-NonCommercial 3.0 Unported License</a>.'
            })
            
            ]
        });
    }

});
