

sap.ui.jsview("ui5applicationiii3.Start", {

createContent: function (oController) {
    
    return new sap.m.Page( {
            title: "Start",
            content: [
                new sap.m.Label({
                text: ""
            }),
            new sap.ui.core.HTML({
              content :   '  <div class="inner">'
              +'  <header style="display: table-cell;">'
              +'<h1>AkuaJs for SAP UI5</h1>'
              +' <h3>The AkuaJs Analytical Engine for SAP UI5</h3>'
              +' </header>'
              +'<div style="display: table-cell;">'
              +' <img src="images/tesseract.png" style="height:100px;vertical-align:botton;margin-left:100px;padding-top:20px" />'
              +'</div>'
              +''
              +''
              +'<section id="downloads" class="clearfix">'
              +' <a href="https://github.com/Qrist0ph/AkuaJs-UI5/blob/master/bin/AkuaJs-UI5.zip" id="download-zip" class="button"><span>Download .zip</span></a>'
              + '<a href="https://github.com/Qrist0ph/AkuaJs-UI5" id="view-on-github" class="button"><span>View on GitHub</span></a>'
              + '<a href="http://qrist0ph.github.io/AkuaJs/" id="view-on-akuajs" class="button"><span>AkuaJs Library</span></a>'
              +'</section>'
              +''  
              +'<div id="wrapper"> <h3>Why use AkuaJs</h3>'
              +'<ul>'
              +'<li>Create awesome Visualizations based on one unified Data Model</li>'
              +'<li>Choose from a variety of different charts</li>'
              +'<li>Build interactive maps to display sales or financial information </li>'
              +'<li>Ready for mobile app development</li>'
              +'<li>Easily extend it to incorporate your favorite charting engine</li>'
              +' <li>Free for non commercial usage and during development</li>'
              +''
              +'</ul>'
              +'</div>'
              +''
              +''
              +'<h3>Using AkuaJs</h3>'
              +'Add dependencies to the head section of your main html:'
              +'<pre><code>' 
              + '&lt;script src=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/libs/D3/d3.min.js&quot;&gt;&lt;/script&gt;    <br/>'
              +'&lt;script data-main=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/main.js&quot; src=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/libs/require.js&quot;&gt;&lt;/script&gt;<br/>'
              +'&lt;link rel=&quot;stylesheet&quot; href=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/libs/nvd3'
              + '</code></pre>'
              +''
              +''
              +''
              +'Use it like that: '              
               +'<pre><code>' 
            +'&lt;!DOCTYPE html&gt;<br/>'
+'&lt;html&gt;<br/>'
+'&lt;head&gt;<br/>'
+'    &lt;script src=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/libs/D3/d3.min.js&quot;&gt;&lt;/script&gt;    <br/>'
+'    &lt;script data-main=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/main.js&quot; src=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/libs/require.js&quot;&gt;&lt;/script&gt;<br/>'
+'    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://rawgit.com/Qrist0ph/AkuaJs/latest/dist/plain/libs/nvd3/nv.d3.min.css&quot; type=&quot;text/css&quot; /&gt;    <br/>'
+'    <br/>'
+'    &lt;script src=&quot;https://openui5.hana.ondemand.com/resources/sap-ui-core.js&quot;<br/>'
+'            id=&quot;sap-ui-bootstrap&quot;<br/>'
+'            data-sap-ui-libs=&quot;sap.m&quot;<br/>'
+'            data-sap-ui-theme=&quot;sap_bluecrystal&quot;&gt;<br/>'
+'    &lt;/script&gt;<br/>'
+'   <br/>'
+'&lt;script&gt;<br/>'
+'  jQuery.sap.registerModulePath(&#39;AkuaJs&#39;, &#39;https://rawgit.com/Qrist0ph/AkuaJs-UI5/latest/build/AkuaJs&#39;);<br/>'
+'  jQuery.sap.require(&quot;AkuaJs.PieChart&quot;); <br/>'
+'  eJune = E(D(&quot;Month&quot;), &quot;June&quot;);<br/>'
+'  eAugust = E(D(&quot;Month&quot;), &quot;August&quot;);<br/>'
+'  ePoland = E(D(&quot;Country&quot;), &quot;Poland&quot;);        <br/>'
+'  eCar = E(D(&quot;Product&quot;), &quot;Car&quot;);<br/>'
+'  eBike = E(D(&quot;Product&quot;), &quot;Bike&quot;);<br/>'
+'  eBoat = E(D(&quot;Product&quot;), &quot;Boat&quot;);<br/>'
+'  eCost = E(D(&quot;Measure&quot;), &quot;Costs&quot;);<br/>'
+'  eRevenue = E(D(&quot;Measure&quot;), &quot;Revenue&quot;);                   <br/>'
+'  new AkuaJs.PieChart({<br/>'
+'                        axis0: A({<br/>'
+'                        crosslists:<br/>'
+'                        [<br/>'
+'                           TCL([<br/>'
+'                                T([eCar]), T([eBike]), T([eBoat])<br/>'
+'                            ])<br/>'
+'                        ]<br/>'
+'                    }),<br/>'
+'                    slicer: T([eCost]),<br/>'
+'<br/>'
+'					connection :[ <br/>'
+'                                 T([eAugust, eCar, eCost],440)<br/>'
+'                                ,T([eAugust, eBike, eCost],77)    <br/>'
+'                                ,T([eAugust, eBoat, eCost],120)],<br/>'
+'                   colors:[&quot;#FFD700&quot;, &quot;#F4A460&quot;,&quot;#990000&quot;],<br/>'
+'                   numberFormat:&#39;,.2&#39;<br/>'
+'<br/>'
+' }).placeAt(&#39;content&#39;)<br/>'
+'&lt;/script&gt;<br/>'
+'&lt;/head&gt;<br/>'
+'&lt;body class=&quot;sapUiBody&quot; role=&quot;application&quot;&gt;<br/>'
+'    &lt;div id=&quot;content&quot;&gt;&lt;/div&gt;<br/>'
+'&lt;/body&gt;<br/>'
+'&lt;/html&gt;<br/>'
              + '</code></pre>'
             
            })
            
            ]
        });
    }

});
